export const LOGIN = 'LOGIN';
export const LOGOUT = 'LOGOUT';
export const GET_UNSOLVED_PROBLEM = 'GET_UNSOLVED_PROBLEM';
export const GET_SOLVED_PROBLEM = 'GET_SOLVED_PROBLEM';
export const CHANGE_TO_UNSOLVED_PROBLEM = 'CHANGE_TO_UNSOLVED_PROBLEM';
export const CHANGE_TO_SOLVED_PROBLEM = 'CHANGE_TO_SOLVED_PROBLEM';
